### ISSUE TITLE
Prettier output when failing to checkout

### ISSUE THREAD

**Issue by dimitryvolkov** [idobh2/node-gitcheckout-cli#1]
First let me say this is an amazing and useful tool, good job!

Currently, when the tool fails to checkout (when changes would be overwritten by the checkout for example), an ugly error message is printed, e.g:
```
Failed to execute:
{ Error: Command failed: git checkout branchname
error: Your local changes to the following files would be overwritten by checkout
...
Aborting

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'git checkout branchname' }
```

Please consider printing a friendlier version of the error message.

**Comment by idobh2** [comment]
Fixed in 1.0.4 (commit 74f273c655ae5eb7360623b482a619822b7a34e6)
